image: java:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - maven
  script:
    - echo "Refreshing PATH"
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")
    - echo $env:Path
    - echo "Building Muse with Maven"
    - mvn -B compile --file pom.xml

test:
  stage: test
  tags:
    - maven
  script:
    - mvn test