image: java:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Refreshing PATH"
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")
    - echo "Moving to Muse Directory"
    - cd code/Muse
    - echo "Building Muse with Maven"
    - mvn clean verify
    - mvn clean compile

test:
  stage: test
  script:
    - mvn clean test